name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer and dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk signfile libc6-dev
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build Android APK with Buildozer
        run: |
          buildozer android debug
